### ISSUE TITLE
Huggingface models requiring authentication

### ISSUE THREAD

**Issue by axeloh** [runpod-workers/worker-infinity-embedding#7]
First of all, thanks for the great work :) 

I am deploying RunPod serverless endpoints using the worker-infinity image, and querying using the OpenAI SDK (with Runpod API key as `api_key` and the runpod endpoint as the `base_url`. 

However, some of the huggingface models require authentication, for instance the [Nvidia NV Embed model ](https://huggingface.co/nvidia/NV-Embed-v1). 

I can see the following from the pod log: 
`Cannot access gated repo for url https://huggingface.co/nvidia/NV-Embed-v1/resolve/main/config.json.
Access to model nvidia/NV-Embed-v1 is restricted. You must be authenticated to access it.`

Is there any support for overcoming this?

**Comment by michaelfeil** [comment]
Have you tried using a `HF_TOKEN` env variable?

**Comment by axeloh** [comment]
No, could try that. Is it attempted read by Infinity?

**Comment by axeloh** [comment]
It worked, thanks :)
